services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rioja_backend_dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rioja_frontend_dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      # - VITE_API_URL=http://127.0.0.1:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    container_name: rioja_db_dev
    env_file:
      - ./backend/.env.dev
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-rioja_password}
    #   MYSQL_DATABASE: ${MYSQL_DB:-rioja_db}
    #   MYSQL_USER: ${MYSQL_USER:-rioja_user}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD:-rioja_password}
    volumes:
      - rioja_mysql_data_dev:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD:-rioja_password}"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  rioja_mysql_data_dev: