services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: rioja_backend_prod
    env_file:
      - ./backend/.env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: rioja_frontend_prod
    # ports:
    #   - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: rioja_db_prod
    env_file:
      - ./backend/.env.prod
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-rioja_password}
    #   MYSQL_DATABASE: ${MYSQL_DB:-rioja_db}
    #   MYSQL_USER: ${MYSQL_USER:-rioja_user}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD:-rioja_password}
    volumes:
      - rioja_mysql_data_prod:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD:-rioja_password}"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  rioja_mysql_data_prod: