# Generated by Django 6.0.3 on 2026-07-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itse',
            name='distrito',
            field=models.CharField(blank=True, default='RIOJA', max_length=100, null=True),
        ),
    ]
