# Generated by Django 6.0.3 on 2026-05-01 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='inspectores_digitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspectores',
            },
        ),
        migrations.CreateModel(
            name='ItseInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('inspector', models.ForeignKey(db_column='inspector_id', on_delete=django.db.models.deletion.PROTECT, related_name='itse_asignadas', to='app_lf_itse.inspector')),
                ('itse', models.ForeignKey(db_column='itse_id', on_delete=django.db.models.deletion.CASCADE, related_name='inspectores', to='app_lf_itse.itse')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='itse_inspectores_digitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'itse_inspectores',
            },
        ),
    ]
