# Generated by Django 6.0.3 on 2026-05-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciafuncionamiento',
            name='dias_atencion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='licenciafuncionamiento',
            name='numero_folios',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
