# Generated by Django 6.0.3 on 2026-07-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0002_itse_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='itse',
            name='informe',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
